language: java
jdk:
  - openjdk8

## Building and testing
script:
  mvn clean install

## Only build email-spring-boot-starter
before_deploy:
  - cd $BUILDING_FOLDER
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - mvn --settings .settings.xml clean deploy -DskipTests=false -Dmaven.javadoc.skip=false -B -U -Prelease

## Create release in Github
deploy:
  provider: releases
  api_key:
    secure: hhqO92JMiFylf5QXJ2zk20MMBkyDEJzxV4LcQ0wY+k1CVm7HL/AiqPtEvXnzrxdaZOp4+a3nthCPaBNZY7UAYIFZaQgB6+FYaOvXqxg/RWghJ8s68/bKfGeIkqFWgNvVaM+38Bd4+kmFD6uT5mKfORjkTm3UKa3MQgbWeUHzf6bWHaiapMpte2Um2gYIwLB8HAW13m7n7OXt8atOa9UY4qSZOllnKFUwhXZMQltSSAbMKzR0DNhli2sqxBQjJLvARsk3Anw1LNMhiQa4zG2oHWuG5CpwQja1u9yMj6jm30LNRBImgqFkjhEXblbRedVHwIKJNCCFbcPE+uw3lJ0beAK3+bkTSzq+qsb2q0EUYd9PmOOTIXaWXdS4+Ib0b0pQ748BrWpZXjapoZ8p5G582CRnQTEeDXtkTOMT7avQZjy9fyF/KnIucJXNdnCqUCabat5xlzwKC2OgXYZmGxnfOqbnPLHuwwQVgwiCtr+4dbxBZ55Cylyvjo/SlNvS42I/xQwx02HSpsFR8T+NoaaRcstdNnyInRNyZbAK4twvYCXiyELyqY6VDhdZs0RqCLadvwFO8oOFE1NR9mBkvQwFxw328Cdt7rIvceW5j2yWxL+2m2Ahpy/jXY5x7I4x0kzO3NbF7OkNJvZ08jFYwGPloZqFEPAvPt0VH1ygfSe/EJ4=
  file:
    - "target/email-spring-boot-starter-$project_version.jar"
    - "target/email-spring-boot-starter-$project_version-javadoc.jar"
    - "target/email-spring-boot-starter-$project_version-sources.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: 57blocks/email-spring-boot
  name: $project_version

cache:
  directories:
    - ~/.m2/repository

env:
  global:
    - BUILDING_FOLDER="`pwd`/email-spring-boot-starter"

notifications:
  slack:
    on_pull_requests: false
    rooms:
      secure: XcJQNlXiuwnpUnO6QjY+vtAsbgcZuLGWcBcfsFTo7Fco/bj3y+ECa/hnRuElGHRxh4GarsQKFp9+OTrFcWlXVAnmDNtLebvlnxL5llSuhth88YOotEkjcc1IQgd0hLHjYTvVLrCFF5QD+tKfbPzPpdGZ60csU9bS+VVfWCJn/T3s/eyKvJrW1e1fWoUf/MfKhp/sqlJcceVlgzHaHRREbJlka5nju9WbfJCUIolyTR+U+kaaPfAwzVdum5X6g5Dc4Egu+8nRudcu7YPN9R7xbuV3VEizfDhAiOPBHbS4xKzCtR+lJpAjrJEvyR6yG0xPH+iMo5v97tTv1jbLJAoR8QyMsNHcBlrCalzOfZIs6gi3o06IiksRlAvZgbj8dEaxXsQajZS6XLLUZYzonUy+BLfAtVbqKg6TczmEbpYbt6jLm0yCnhAFYugZq8acWeWUdYXn2TdPs5O5LA1/pRJpFz8Mic78fJW5q4W6jsulHz73MnDQUeVWoOzmlauGICVsqOd67xz/CfjJLdUYfB/xnAiPjorODKHoWJz4Tl5tULxKQ6gv3saDoeqNWZFbA/49fsLOphGca6lamKWfCXQZs+3XFFTcEaQyyvyE31A4hwo0zU9VQKOeLnVe/QAHpmrD3OwqfxczauX4zO3JOb1woynCqinh+NUSxTrdVHogjAo=
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}` by %{author}."
      - "Execution time: *%{duration}*"
      - "Commit message: %{commit_message}"